version: '3'

services:
  prestashop:
    image: kikz01/be_18858:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    environment:
      PS_INSTALL_AUTO: ${PS_INSTALL_AUTO:-1}  #to instaluje cos tam
      DB_PASSWD: ${DB_PASSWD:-student}
      DB_NAME: ${DB_NAME:-be_188581_db}
      DB_SERVER: ${DB_SERVER:-db}
      DB_PREFIX: ${DB_PREFIX:-ps_}
      PS_DOMAIN: ${PS_DOMAIN:-localhost:18858}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL:-install-dev}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN:-admin-dev}
      PS_COUNTRY: ${PS_COUNTRY:-pl}
      PS_LANGUAGE: ${PS_LANGUAGE:-pl}
      PS_DEV_MODE: ${PS_DEV_MODE:-0}
      ADMIN_MAIL: ${ADMIN_MAIL:-demo@prestashop.com}
      ADMIN_PASSWD: ${ADMIN_PASSWD:-prestashop_demo}
      PS_ERASE_DB: ${PS_ERASE_DB:-1}  #to do dropowania bazy musi byc install auto, dorpuje jak baza istnieje jak nie to nie
    command: ["/tmp/launch.sh"]
    ports:
      - "18858:443"
    networks:
      - admin-mysql_default

networks:
  admin-mysql_default:
    external: true
