<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFriwgid\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFriwgid/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFriwgid.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFriwgid\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFriwgid\appDevDebugProjectContainer([
    'container.build_hash' => 'Friwgid',
    'container.build_id' => '8dc7b154',
    'container.build_time' => 1703287686,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFriwgid');
